<?php
$string['install']="Php-Stats %php-stats-ver% - Updader";
$string['lang_select']="Select your language:";
$string['license']="<b>License Agreement</b>";
$string['license_ok']="I ACCEPT";
$string['license_no']="I DON'T ACCEPT";
$string['license_agree']="<b>By proceed you agree at this License Agreement</b>";
$string['next']="Next ->";
$string['end']=">> End <<";
$string['box_title']="Warning:";
$string['box_title_ok']="Information:";
$string['done']="Update successfully done.";

// ERROR HANDLING
$error['no_min_ver']="<b>ERROR</b>: Php-Stats PRO 0.1.3 or later is required for update.";
$error['no_ver_detect']="<b>ERROR</b>: Unable to detect Php-Stats PRO version.";
$error['noupdateneed']="No update needed for your Php-Stats PRO.";
$error['error_updating']="<b>WARNING: CRITICAL ERROR</b><br><br>You can annotate the possible errors and bring them on the support forum at : <a href=\"http://www.php-stats.com/forum/\" target=\"_BLANK\">http://www.php-stats.com/forum/</a><br>
                          <br><b>Update is interrupted.</b>";
$error['nowrite_server']="<b>WARNING:</b> It's impossible to write files on your server.<br>Set 777 permits to option folder<br>otherwise if you decide to continue you will use the files without support of writing Web<br>";
$error['nowrite_server_1']="<b>WARNING:</b> It's impossible to write files on your server.<br>The files without support of writing on the Server will be used.<br>In the future, if you want use the files with support of writing,<br>you must set the permissions 777 to the option foldere and copy all files, in files_Write folder,<br> in the principal Php-Stats directory and then launch the create-options.php file";
?>