<?php
$string['install']="Php-Stats %php-stats-ver% - Updader";
$string['lang_select']="Selezionare la ligua:";
$string['license']="<b>Condizioni di licenza:</b>";
$string['license_ok']="ACCETTO";
$string['license_no']="NON ACCETTO";
$string['license_agree']="<b>Procedendo accetti tutte queste condizioni di licenza</b>";
$string['next']="Avanti ->";
$string['end']=">> Fine <<";
$string['box_title']="Attenzione:";
$string['box_title_ok']="Informazione:";
$string['done']="Update effettuato correttamente.";

// ERROR HANDLING
$error['no_min_ver']="<b>ERRORE</b>: Per eseguire l'update è necessario Php-Stats PRO 0.1.3 o successivo.";
$error['no_ver_detect']="<b>ERRORE</b>: Impossibile determinare la versione corrente di Php-Stats PRO.";
$error['noupdateneed']="Nessun update necessario per la vostra versione di Php-Stats PRO.";
$error['error_updating']="<b>ATTENZIONE: ERRORE CRITICO</b><br><br> Si consiglia di prendere nota degli eventuali errori e riportarli sul forum di supporto: <a href=\"http://www.php-stats.com/forum/\" target=\"_BLANK\">http://www.php-stats.com/forum/</a><br>
                          <br>L'upgrade non è stato terminato correttamente e pertanto lo Php-Stats PRO potrebbe funzionare in modo imprevedibile.";
$error['nowrite_server_1']="<b>ATTENZIONE:</b> Non è possibile scrivere files sul tuo server.<br>Setta i permessi 777 alla cartella option<br>altrimenti se decidi di continuare verrano usati i files senza supporto di scrittura via WEB";
$error['nowrite_server']="<b>ATTENZIONE:</b> Non è possibile scrivere files sul tuo server.<br>Verranno utilizzati i files senza supporto di scrittura sul Server<br>Nel futuro, se intendi usare i files con supporto di scrittura,<br>dovrai settare i permessi 777 alla cartella option<br>copiare tutti i filea, presenti nella cartella files_Write, nella directory principale di Php-Stats<br>ed eseguire il file create-options.php<br>";
?>